development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: zoowedding_development
  pool:     5

test: &test
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: zoowedding_test
  pool:     5

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: zoowedding_production
  pool:     5
